"""empty message

Revision ID: 0002cd8be36f
Revises: 22d57adbc78d
Create Date: 2016-12-29 09:54:57.542832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002cd8be36f'
down_revision = '22d57adbc78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_record', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('pickup_record', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_record', 'lng')
    op.drop_column('pickup_record', 'lat')
    # ### end Alembic commands ###
