"""empty message

Revision ID: 55a5e7ad5555
Revises: 0002cd8be36f
Create Date: 2016-12-30 21:32:13.841685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a5e7ad5555'
down_revision = '0002cd8be36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_record', sa.Column('geocode_address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_record', 'geocode_address')
    # ### end Alembic commands ###
