"""empty message

Revision ID: 6cd2c17ac72b
Revises: 0c1a05f45bc9
Create Date: 2016-12-19 19:21:14.218699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd2c17ac72b'
down_revision = '0c1a05f45bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PickupDate',
    sa.Column('pickupDateId', sa.Integer(), nullable=False),
    sa.Column('pickupDate', sa.String(length=20), nullable=False),
    sa.Column('openTime', sa.DateTime(), nullable=False),
    sa.Column('closeTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pickupDateId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PickupDate')
    # ### end Alembic commands ###
