"""empty message

Revision ID: b5e17459ff10
Revises: 9967e9d52599
Create Date: 2016-12-19 20:02:02.467318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e17459ff10'
down_revision = '9967e9d52599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emailAddress', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('emailAddress'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.INTEGER(), server_default=sa.text(u'nextval(\'"user_userId_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('emailAddress', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userId', name=u'user_pkey'),
    sa.UniqueConstraint('emailAddress', name=u'user_emailAddress_key'),
    sa.UniqueConstraint('name', name=u'user_name_key')
    )
    op.drop_table('admin_user')
    # ### end Alembic commands ###
